  {{- range $_, $v := .Values.auths -}}
  {{- $auth := printf "%v:%v" $v.username $v.password | b64enc }}
  {{- $_ := set $v "auth" $auth -}}
  {{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: registry-cred
  namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    {{ .Values | toJson | b64enc }}
